### ISSUE TITLE
questions about loss

### ISSUE THREAD

**Issue by IcyFeather233** [zou-group/textgrad#18]
Hi I noticed that in `textgrad/tasks/__init__.py`, there are many eval functions: `MultiFieldTokenParsedEvaluation` `StringBasedFunction`, also in `textgrad/loss.py`, there are other eval functions: `TextLoss` `MultiFieldEvaluation` `MultiChoiceTestTime` 

I am a little confused about what eval function I should use, are there some detailed information about how to chose which function to use in detail? Why [BBH uses `MultiFieldTokenParsedEvaluation`](https://github.com/zou-group/textgrad/blob/main/textgrad/tasks/__init__.py#L60) while [GSM8K uses `StringBasedFunction`](https://github.com/zou-group/textgrad/blob/main/textgrad/tasks/__init__.py#L85)?

**Comment by IcyFeather233** [comment]
By the way, If I want the result to include a certain string(like [TOKEN]), which loss function should I use? Or how should I modify the code? Can you give me some advice? Thank you very much!

**Comment by mertyg** [comment]
Cool! So if you look at object counting ([here](https://github.com/zou-group/textgrad/blob/main/textgrad/tasks/__init__.py#L28)), we use this string-based evaluation: https://github.com/zou-group/textgrad/blob/main/textgrad/tasks/__init__.py#L42 .
This basically looks at the last numerical value, and checks if it matches the ground truth answer.

More generally for BBH tasks such as word sorting, we do not have numerical values to compare. E.g., in word sorting we need to compare two lists. Since this is much more tricky to do in general, we do this by making another language model call and asking it to compare two lists -- and use it as the loss function. That's what `MultiFieldEvaluation` does at a high level. `MultiFieldTokenParsedEvaluation` basically only adds parsing functionality (i.e., asks the evaluation to be returned within two HTML tags. 

If you want the result to include a certain string, i think you can leverage constraints. e.g., you can use something like 

`tg.TGD(parameters=parameters, constraints=["The output should end with <TOKEN>"])`. Basically, this lets the optimizer see the natural language constraints you specify through the `constraints` argument.

Hope this helps!

**Comment by IcyFeather233** [comment]
Below is my understanding of TextGrad, I am not sure if it is correct. 

There is an inference model and an evaluation model (backward engine). The inference model answers questions, and then there is a loss function that calls the model from the backward engine to analyze the response. Subsequently, the optimizer will call the model from the backward engine to optimize the prompt based on this analysis.

However, if I need the analysis from the loss function to **not be the model's inference analysis**, for example, I want to manually write a judgment of right and wrong, manually write an analysis for the correct cases and incorrect cases, these two analyses are given, and I only want the model to do the optimizer's optimization work, combining the given analyses with the question and the answer to optimize the prompt, how should I modify it? All of the current loss classes seems to require calling the model for inference.
